spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}:3306/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
rootDirectory: /home/${USER}/app/
officialDocDirectory: ${rootDirectory}oficios/
userProfileImgDirectory: ${rootDirectory}fotosPerfil/

